SELECT 
    SUPPLIER_NORMALIZED,
    CASE
        WHEN SUM(TOTAL_SPEND_USD) > 3500000 THEN '>3.5M'
        WHEN SUM(TOTAL_SPEND_USD) > 2000000 AND SUM(TOTAL_SPEND_USD) <= 3500000 THEN '2-3.5M'
        WHEN SUM(TOTAL_SPEND_USD) > 1000000 AND SUM(TOTAL_SPEND_USD) <= 2000000 THEN '1-2M'
        WHEN SUM(TOTAL_SPEND_USD) > 250000 AND SUM(TOTAL_SPEND_USD) <= 1000000 THEN '250K-1M'
        WHEN SUM(TOTAL_SPEND_USD) > 100000 AND SUM(TOTAL_SPEND_USD) <= 250000 THEN '100-250K'
        WHEN SUM(TOTAL_SPEND_USD) > 50000 AND SUM(TOTAL_SPEND_USD) <= 100000 THEN '50-100K'
        WHEN SUM(TOTAL_SPEND_USD) > 25000 AND SUM(TOTAL_SPEND_USD) <= 50000 THEN '25-50K'
        WHEN SUM(TOTAL_SPEND_USD) > 10000 AND SUM(TOTAL_SPEND_USD) <= 25000 THEN '10-25K'
        WHEN SUM(TOTAL_SPEND_USD) > 5000 AND SUM(TOTAL_SPEND_USD) <= 10000 THEN '5-10K'
        WHEN SUM(TOTAL_SPEND_USD) > 0 AND SUM(TOTAL_SPEND_USD) <= 5000 THEN '0-5K'
        WHEN SUM(TOTAL_SPEND_USD) <= 0 THEN '<=$0'
    END AS SPEND_TIERS_ANNUAL,
    CASE
        WHEN SUM(TOTAL_SPEND_USD) >= 1000000 THEN 'STRATEGIC'
        WHEN SUM(TOTAL_SPEND_USD) < 1000000 AND SUM(TOTAL_SPEND_USD) >= 50000 THEN 'TACTICAL'
        WHEN SUM(TOTAL_SPEND_USD) < 50000 AND SUM(TOTAL_SPEND_USD) > 0 THEN 'TAIL'
        WHEN SUM(TOTAL_SPEND_USD) <= 0 THEN 'Zero or Negative'
    END AS SOURCING_SEGMENT
FROM TBC_SPEND_FINAL
WHERE FISCAL_YEAR = 'FY_2022'
GROUP BY SUPPLIER_NORMALIZED
ORDER BY SUPPLIER_NORMALIZED;


SELECT 
    SUPPLIER_NORMALIZED,
    SUM(TOTAL_SPEND_USD) AS total_spend_per_supplier,
    LISTAGG(DISTINCT SOURCE_DATA, ', ') WITHIN GROUP (ORDER BY SOURCE_DATA) AS SOURCE_DATA,
    LISTAGG(DISTINCT FILE_NAME, ', ') WITHIN GROUP (ORDER BY FILE_NAME) AS FILE_NAME
FROM TBC_SPEND_FINAL
WHERE FISCAL_YEAR = 'FY_2022'
GROUP BY SUPPLIER_NORMALIZED
ORDER BY total_spend_per_supplier DESC;


