SELECT DISTINCT FISCAL_MONTH, FISCAL_QUARTER, FISCAL_YEAR, TRANSACTION_DATE FROM DF_TBC_SPEND_FINAL
--WHERE FISCAL_YEAR = 'FY_2024';
WHERE INVOICE_PAID_DATE IS null AND SOURCE_DATA = 'Concur'
ORDER BY TRANSACTION_DATE DESC;

-- Count of records from the first query minus the second query

SELECT COUNT (*) AS DIFF_COUNT_1
FROM (
    SELECT FISCAL_YEAR
    FROM DF_TBC_SPEND_FINAL
    WHERE FISCAL_YEAR = 'FY_2024'
    MINUS
    SELECT FISCAL_YEAR
    FROM DF_TBC_SPEND_FINAL
    WHERE INVOICE_PAID_DATE IS NULL 
);

SELECT COUNT (*) AS DIFF_COUNT_2
FROM (
    SELECT FISCAL_YEAR
    FROM DF_TBC_SPEND_FINAL
    WHERE INVOICE_PAID_DATE IS NULL AND SOURCE_DATA = 'Concur'
    MINUS
    SELECT FISCAL_YEAR
    FROM DF_TBC_SPEND_FINAL
    WHERE FISCAL_YEAR = 'FY_2024'
);

SELECT FISCAL_YEAR,FISCAL_QUARTER, FISCAL_YEAR, SOURCE_DATA
FROM DF_TBC_SPEND_FINAL
WHERE INVOICE_PAID_DATE IS NULL AND FISCAL_YEAR <> 'FY_2024';





UPDATE DF_TBC_SPEND_FINAL 
SET 
    FISCAL_MONTH = 
        CASE 
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'APR' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 01-APR'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'MAY' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 02-MAY'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'JUN' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 03-JUN'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'JUL' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 04-JUL'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'AUG' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 05-AUG'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'SEP' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 06-SEP'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'OCT' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 07-OCT'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'NOV' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 08-NOV'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'DEC' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 09-DEC'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'JAN' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 10-JAN'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) = 'FEB' THEN 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 11-FEB'
            ELSE 'FY_' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' 12-MAR' -- The ELSE handles 'MAR'
        END,
    FISCAL_QUARTER =
        CASE 
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) IN ('APR', 'MAY', 'JUN') THEN 'FY' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' Q1'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) IN ('JUL', 'AUG', 'SEP') THEN 'FY' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' Q2'
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) IN ('OCT', 'NOV', 'DEC') THEN 'FY' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' Q3'
            ELSE 'FY' || SUBSTR(TRANSACTION_DATE, 8, 2) || ' Q4' -- The ELSE here handles 'JAN', 'FEB', and 'MAR'
        END,
    FISCAL_YEAR = 
        CASE 
            WHEN SUBSTR(TRANSACTION_DATE, 4, 3) >= 'APR' THEN 'FY_' || TO_CHAR(TO_NUMBER(SUBSTR(TRANSACTION_DATE, 8, 2)) + 2000)
            ELSE 'FY_' || TO_CHAR(TO_NUMBER(SUBSTR(TRANSACTION_DATE, 8, 2)) + 1999)
        END
WHERE FISCAL_YEAR = 'FY_2024';

