  
-- verify shared values and collect only the rows to update

SELECT
    SIDE.SUPPLIER_NBR,
    SIDE.SUPPLIER_ADDRESS_1,
    SIDE.SUPPLIER_ADDRESS_2,
    SIDE.SUPPLIER_ADDRESS_3,
    SIDE.SUPPLIER_CITY,
    SIDE.SUPPLIER_COUNTRY,
    SIDE.SUPPLIER_STATE,
    SIDE.SUPPLIER_TYPE,
    SIDE.SUPPLIER_ZIP_POSTAL_CDE,
    COUNT(*) AS ROW_COUNT,
    SUM(FINAL.SPEND_USD) AS TOTAL_SPEND_USD
FROM DF_SUB_SPEND_FINAL FINAL
INNER JOIN DF_SUB_UPDATE_TABLE SIDE
ON (FINAL.SUPPLIER_NBR = SIDE.SUPPLIER_NBR)
WHERE FINAL.SUPPLIER_ADDRESS_1 IS NULL AND  SOURCE_DATA = 'Invoice'
GROUP BY 
    SIDE.SUPPLIER_NBR,
    SIDE.SUPPLIER_ADDRESS_1,
    SIDE.SUPPLIER_ADDRESS_2,
    SIDE.SUPPLIER_ADDRESS_3,
    SIDE.SUPPLIER_CITY,
    SIDE.SUPPLIER_COUNTRY,
    SIDE.SUPPLIER_STATE,
    SIDE.SUPPLIER_TYPE,
    SIDE.SUPPLIER_ZIP_POSTAL_CDE
;

SELECT
    FINAL.SUPPLIER_NBR,
    FINAL.SUPPLIER_ADDRESS_1,
    FINAL.SUPPLIER_ADDRESS_2,
    FINAL.SUPPLIER_ADDRESS_3,
    FINAL.SUPPLIER_CITY,
    FINAL.SUPPLIER_COUNTRY,
    FINAL.SUPPLIER_STATE,
    FINAL.SUPPLIER_TYPE,
    FINAL.SUPPLIER_ZIP_POSTAL_CDE,
    COUNT(*) AS ROW_COUNT,
    SUM(FINAL.SPEND_USD) AS TOTAL_SPEND_USD
FROM DF_SUB_SPEND_FINAL FINAL
INNER JOIN DF_SUB_UPDATE_TABLE SIDE
ON (FINAL.SUPPLIER_NBR = SIDE.SUPPLIER_NBR)
WHERE FINAL.SUPPLIER_ADDRESS_1 IS NULL AND  SOURCE_DATA = 'Invoice'
GROUP BY 
    FINAL.SUPPLIER_NBR,
    FINAL.SUPPLIER_ADDRESS_1,
    FINAL.SUPPLIER_ADDRESS_2,
    FINAL.SUPPLIER_ADDRESS_3,
    FINAL.SUPPLIER_CITY,
    FINAL.SUPPLIER_COUNTRY,
    FINAL.SUPPLIER_STATE,
    FINAL.SUPPLIER_TYPE,
    FINAL.SUPPLIER_ZIP_POSTAL_CDE
;

-- Update QA
-- 1. select the blanks in the supplier related fields
SELECT 
    FISCAL_YEAR,
    FISCAL_QUARTER,
    SD_DIVERSITY_ATTRIBUTES,
    SOURCE_DATA,
    SUPPLIER_ADDRESS_1,
    SUPPLIER_ADDRESS_2,
    SUPPLIER_ADDRESS_3,
    SUPPLIER_CITY,
    SUPPLIER_COUNTRY,
    SUPPLIER_ERP,
    SUPPLIER_NBR,
    SUPPLIER_NORMALIZED,
    SUPPLIER_PARENT,
    SUPPLIER_STATE,
    SUPPLIER_TYPE,
    SUPPLIER_ZIP_POSTAL_CDE,
    SUM(SPEND_USD) AS TOTAL_SPEND_USD,
    COUNT(SOURCE_DATA) AS ROW_COUNT
FROM DF_SUB_SPEND_FINAL WHERE SUPPLIER_ADDRESS_1 IS NULL AND SOURCE_DATA = 'Invoice'
GROUP BY
    FISCAL_YEAR,
    FISCAL_QUARTER,
    SD_DIVERSITY_ATTRIBUTES,
    SOURCE_DATA,
    SUPPLIER_ADDRESS_1,
    SUPPLIER_ADDRESS_2,
    SUPPLIER_ADDRESS_3,
    SUPPLIER_CITY,
    SUPPLIER_COUNTRY,
    SUPPLIER_ERP,
    SUPPLIER_NBR,
    SUPPLIER_NORMALIZED,
    SUPPLIER_PARENT,
    SUPPLIER_STATE,
    SUPPLIER_TYPE,
    SUPPLIER_ZIP_POSTAL_CDE
;
-- 2. select the distinct supplier related fields before and after the update
SELECT 
    FISCAL_YEAR,
    COUNT(DISTINCT SUPPLIER_ADDRESS_1) AS DISTINCT_SUPPLIER_ADDRESS_1_,
    COUNT(DISTINCT SUPPLIER_ADDRESS_2) AS DISTINCT_SUPPLIER_ADDRESS_2,
    COUNT(DISTINCT SUPPLIER_ADDRESS_3) AS DISTINCT_SUPPLIER_ADDRESS_3,
    COUNT(DISTINCT SUPPLIER_CITY) AS DISTINCT_SUPPLIER_CITY,
    COUNT(DISTINCT SUPPLIER_COUNTRY) AS DISTINCT_SUPPLIER_COUNTRY,
    COUNT(DISTINCT SUPPLIER_NBR) AS DISTINCT_SUPPLIER_NBR,
    COUNT(DISTINCT SUPPLIER_STATE) AS DISTINCT_SUPPLIER_STATE,
    COUNT(DISTINCT SUPPLIER_TYPE) AS DISTINCT_SUPPLIER_TYPE,
    COUNT(DISTINCT SUPPLIER_ZIP_POSTAL_CDE) AS DISTINCT_SUPPLIER_ZIP_POSTAL_CDE
FROM DF_SUB_SPEND_FINAL WHERE SOURCE_DATA = 'Invoice'
GROUP BY
    FISCAL_YEAR
;
