SELECT
    BUSINESS_GROUP,
    SOURCE_DATA,
    INVOICE_DATE,
    SUPPLIER_NBR,
    SUPPLIER_NORMALIZED,
    SUPPLIER_PARENT,
    HOLDING_COMPANY
FROM SUB_SPEND_FINAL
WHERE SUPPLIER_NORMALIZED LIKE '%VERITAS COMMUNICATIONS%'
AND INVOICE_DATE = (
        SELECT MAX(INVOICE_DATE)
        FROM SUB_SPEND_FINAL
        WHERE SUPPLIER_NORMALIZED LIKE '%VERITAS COMMUNICATIONS%'
    );