-- Update the spend table

-- 1. clean trailing whitespaces
UPDATE SUB_SPEND_FINAL
SET
    SUPPLIER_COUNTRY = TRIM(SUPPLIER_COUNTRY),
    SUPPLIER_STATE = TRIM(SUPPLIER_STATE),
    SUPPLIER_CITY = TRIM(SUPPLIER_CITY)
WHERE 
    SUPPLIER_COUNTRY IS NOT NULL OR
    SUPPLIER_STATE IS NOT NULL OR
    SUPPLIER_CITY IS NOT NULL;
    
-- 2. update supplier country
UPDATE SUB_SPEND_FINAL
SET SUPPLIER_COUNTRY = CASE 
    WHEN SUPPLIER_COUNTRY = 'BRASIL' THEN 'BRAZIL'
    WHEN SUPPLIER_COUNTRY = 'COLUMBIA' THEN 'COLOMBIA'
    WHEN SUPPLIER_COUNTRY = 'NEDERLAND' THEN 'NETHERLANDS'
    WHEN SUPPLIER_COUNTRY = 'THE NETHERLANDS' THEN 'NETHERLANDS'
    WHEN SUPPLIER_COUNTRY = 'ENGLAND' THEN 'UNITED KINGDOM'
    WHEN SUPPLIER_COUNTRY = 'US' THEN 'UNITED STATES'
    -- Add more conditions here if needed
    ELSE SUPPLIER_COUNTRY
END
WHERE SUPPLIER_COUNTRY IN ('BRASIL', 'COLUMBIA', 'NEDERLAND', 'THE NETHERLANDS', 'ENGLAND', 'US');

-- 3. update supplier state
UPDATE SUB_SPEND_FINAL
SET SUPPLIER_STATE = CASE 
    WHEN SUPPLIER_STATE = 'AZ' THEN 'ARIZONA'
    WHEN SUPPLIER_STATE = 'CT' THEN 'CONNECTICUT'
    WHEN SUPPLIER_STATE = 'FL' THEN 'FLORIDA'
    WHEN SUPPLIER_STATE = 'IL' THEN 'ILLINOIS'
    WHEN SUPPLIER_STATE = 'LA' THEN 'LOUISIANA'
    WHEN SUPPLIER_STATE = 'OH' THEN 'OHIO'
    WHEN SUPPLIER_STATE = 'PA' THEN 'PENNSYLVANIA'
    WHEN SUPPLIER_STATE = 'TX' THEN 'TEXAS'
    WHEN SUPPLIER_STATE = 'AL' THEN 'ALABAMA'
    WHEN SUPPLIER_STATE = 'AK' THEN 'ALASKA'
    WHEN SUPPLIER_STATE = 'AR' THEN 'ARKANSAS'
    WHEN SUPPLIER_STATE = 'CA' THEN 'CALIFORNIA'
    WHEN SUPPLIER_STATE = 'CO' THEN 'COLORADO'
    WHEN SUPPLIER_STATE = 'DC' THEN 'DISTRICT OF COLUMBIA'
    WHEN SUPPLIER_STATE = 'GA' THEN 'GEORGIA'
    WHEN SUPPLIER_STATE = 'HI' THEN 'HAWAII'
    WHEN SUPPLIER_STATE = 'ID' THEN 'IDAHO'
    WHEN SUPPLIER_STATE = 'IN' THEN 'INDIANA'
    WHEN SUPPLIER_STATE = 'IA' THEN 'IOWA'
    WHEN SUPPLIER_STATE = 'KS' THEN 'KANSAS'
    WHEN SUPPLIER_STATE = 'KY' THEN 'KENTUCKY'
    WHEN SUPPLIER_STATE = 'ME' THEN 'MAINE'
    WHEN SUPPLIER_STATE = 'MD' THEN 'MARYLAND'
    WHEN SUPPLIER_STATE = 'MA' THEN 'MASSACHUSETTS'
    WHEN SUPPLIER_STATE = 'MI' THEN 'MICHIGAN'
    WHEN SUPPLIER_STATE = 'MN' THEN 'MINNESOTA'
    WHEN SUPPLIER_STATE = 'MS' THEN 'MISSISSIPPI'
    WHEN SUPPLIER_STATE = 'MO' THEN 'MISSOURI'
    WHEN SUPPLIER_STATE = 'MT' THEN 'MONTANA'
    WHEN SUPPLIER_STATE = 'NC' THEN 'NORTH CAROLINA'
    WHEN SUPPLIER_STATE = 'ND' THEN 'NORTH DAKOTA'
    WHEN SUPPLIER_STATE = 'NE' THEN 'NEBRASKA'
    WHEN SUPPLIER_STATE = 'NV' THEN 'NEVADA'
    WHEN SUPPLIER_STATE = 'NH' THEN 'NEW HAMPSHIRE'
    WHEN SUPPLIER_STATE = 'NJ' THEN 'NEW JERSEY'
    WHEN SUPPLIER_STATE = 'NM' THEN 'NEW MEXICO'
    WHEN SUPPLIER_STATE = 'NY' THEN 'NEW YORK'
    WHEN SUPPLIER_STATE = 'OK' THEN 'OKLAHOMA'
    WHEN SUPPLIER_STATE = 'OR' THEN 'OREGON'
    WHEN SUPPLIER_STATE = 'RI' THEN 'RHODE ISLAND'
    WHEN SUPPLIER_STATE = 'SC' THEN 'SOUTH CAROLINA'
    WHEN SUPPLIER_STATE = 'SD' THEN 'SOUTH DAKOTA'
    WHEN SUPPLIER_STATE = 'TN' THEN 'TENNESSEE'
    WHEN SUPPLIER_STATE = 'UT' THEN 'UTAH'
    WHEN SUPPLIER_STATE = 'VT' THEN 'VERMONT'
    WHEN SUPPLIER_STATE = 'VA' THEN 'VIRGINIA'
    WHEN SUPPLIER_STATE = 'WA' THEN 'WASHINGTON'
    WHEN SUPPLIER_STATE = 'WV' THEN 'WEST VIRGINIA'
    WHEN SUPPLIER_STATE = 'WI' THEN 'WISCONSIN'
    WHEN SUPPLIER_STATE = 'WY' THEN 'WYOMING'
    -- For Canadian provinces
    WHEN SUPPLIER_STATE = 'ON' THEN 'ONTARIO'
    WHEN SUPPLIER_STATE = 'QC' THEN 'QUEBEC'
    WHEN SUPPLIER_STATE = 'AB' THEN 'ALBERTA'
    WHEN SUPPLIER_STATE = 'BC' THEN 'BRITISH COLUMBIA'
    WHEN SUPPLIER_STATE = 'SK' THEN 'SASKATCHEWAN'
    -- Add more conditions here if needed
    ELSE SUPPLIER_STATE
END
WHERE SUPPLIER_STATE IN ('AZ', 'CT', 'FL', 'IL', 'LA', 'OH', 'PA', 'TX', 'AL', 'AK', 'AR', 'CA', 'CO', 'DC', 'GA', 'HI', 'ID', 'IN', 'IA', 'KS', 'KY', 'ME', 'MD', 'MA', 
    'MI', 'MN', 'MS', 'MO', 'MT', 'NC', 'ND', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'OK', 'OR', 'RI', 'SC', 'SD', 'TN', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'ON', 'QC', 
    'AB', 'BC', 'SK');

    
------------------------------------------------------------------------------------------------------------------
--Update the diversity table

-- 1. clean trailing whitespaces
UPDATE SUB_SUP_DIV
SET
    SUPPLIER_COUNTRY = TRIM(SUPPLIER_COUNTRY),
    SUPPLIER_STATE = TRIM(SUPPLIER_STATE),
    SUPPLIER_CITY = TRIM(SUPPLIER_CITY)
WHERE 
    SUPPLIER_COUNTRY IS NOT NULL OR
    SUPPLIER_STATE IS NOT NULL OR
    SUPPLIER_CITY IS NOT NULL;
    
-- 2. update supplier country
UPDATE SUB_SUP_DIV
SET SUPPLIER_COUNTRY = CASE 
    WHEN SUPPLIER_COUNTRY = 'CAN' THEN 'CANADA'
    WHEN SUPPLIER_COUNTRY = 'US' THEN 'UNITED STATES'
    -- Add more abbreviations and corresponding full names as needed
    ELSE SUPPLIER_COUNTRY
END
WHERE SUPPLIER_COUNTRY IN ('CAN', 'US');

--3. update supplier state
UPDATE SUB_SUP_DIV
SET SUPPLIER_STATE = CASE 
    WHEN SUPPLIER_STATE = 'AL' THEN 'ALABAMA'
    WHEN SUPPLIER_STATE = 'AK' THEN 'ALASKA'
    WHEN SUPPLIER_STATE = 'AZ' THEN 'ARIZONA'
    WHEN SUPPLIER_STATE = 'AR' THEN 'ARKANSAS'
    WHEN SUPPLIER_STATE = 'CA' THEN 'CALIFORNIA'
    WHEN SUPPLIER_STATE = 'CO' THEN 'COLORADO'
    WHEN SUPPLIER_STATE = 'CT' THEN 'CONNECTICUT'
    WHEN SUPPLIER_STATE = 'DE' THEN 'DELAWARE'
    WHEN SUPPLIER_STATE = 'DC' THEN 'DISTRICT OF COLUMBIA'
    WHEN SUPPLIER_STATE = 'FL' THEN 'FLORIDA'
    WHEN SUPPLIER_STATE = 'GA' THEN 'GEORGIA'
    WHEN SUPPLIER_STATE = 'GU' THEN 'GUAM'
    WHEN SUPPLIER_STATE = 'HI' THEN 'HAWAII'
    WHEN SUPPLIER_STATE = 'IL' THEN 'ILLINOIS'
    WHEN SUPPLIER_STATE = 'IN' THEN 'INDIANA'
    WHEN SUPPLIER_STATE = 'IA' THEN 'IOWA'
    WHEN SUPPLIER_STATE = 'KS' THEN 'KANSAS'
    WHEN SUPPLIER_STATE = 'KY' THEN 'KENTUCKY'
    WHEN SUPPLIER_STATE = 'LA' THEN 'LOUISIANA'
    WHEN SUPPLIER_STATE = 'ME' THEN 'MAINE'
    WHEN SUPPLIER_STATE = 'MD' THEN 'MARYLAND'
    WHEN SUPPLIER_STATE = 'MA' THEN 'MASSACHUSETTS'
    WHEN SUPPLIER_STATE = 'MI' THEN 'MICHIGAN'
    WHEN SUPPLIER_STATE = 'MN' THEN 'MINNESOTA'
    WHEN SUPPLIER_STATE = 'MO' THEN 'MISSOURI'
    WHEN SUPPLIER_STATE = 'MT' THEN 'MONTANA'
    WHEN SUPPLIER_STATE = 'NC' THEN 'NORTH CAROLINA'
    WHEN SUPPLIER_STATE = 'ND' THEN 'NORTH DAKOTA'
    WHEN SUPPLIER_STATE = 'NE' THEN 'NEBRASKA'
    WHEN SUPPLIER_STATE = 'NH' THEN 'NEW HAMPSHIRE'
    WHEN SUPPLIER_STATE = 'NJ' THEN 'NEW JERSEY'
    WHEN SUPPLIER_STATE = 'NM' THEN 'NEW MEXICO'
    WHEN SUPPLIER_STATE = 'NY' THEN 'NEW YORK'
    WHEN SUPPLIER_STATE = 'NV' THEN 'NEVADA'
    WHEN SUPPLIER_STATE = 'OH' THEN 'OHIO'
    WHEN SUPPLIER_STATE = 'OK' THEN 'OKLAHOMA'
    WHEN SUPPLIER_STATE = 'OR' THEN 'OREGON'
    WHEN SUPPLIER_STATE = 'PA' THEN 'PENNSYLVANIA'
    WHEN SUPPLIER_STATE = 'PR' THEN 'PUERTO RICO'
    WHEN SUPPLIER_STATE = 'RI' THEN 'RHODE ISLAND'
    WHEN SUPPLIER_STATE = 'SC' THEN 'SOUTH CAROLINA'
    WHEN SUPPLIER_STATE = 'SD' THEN 'SOUTH DAKOTA'
    WHEN SUPPLIER_STATE = 'TN' THEN 'TENNESSEE'
    WHEN SUPPLIER_STATE = 'TX' THEN 'TEXAS'
    WHEN SUPPLIER_STATE = 'UT' THEN 'UTAH'
    WHEN SUPPLIER_STATE = 'VT' THEN 'VERMONT'
    WHEN SUPPLIER_STATE = 'VA' THEN 'VIRGINIA'
    WHEN SUPPLIER_STATE = 'WA' THEN 'WASHINGTON'
    WHEN SUPPLIER_STATE = 'WV' THEN 'WEST VIRGINIA'
    WHEN SUPPLIER_STATE = 'WI' THEN 'WISCONSIN'
    WHEN SUPPLIER_STATE = 'WY' THEN 'WYOMING'
    WHEN SUPPLIER_STATE = 'AB' THEN 'ALBERTA'
    WHEN SUPPLIER_STATE = 'BC' THEN 'BRITISH COLUMBIA'
    WHEN SUPPLIER_STATE = 'ON' THEN 'ONTARIO'
    WHEN SUPPLIER_STATE = 'QC' THEN 'QUEBEC'
    WHEN SUPPLIER_STATE = 'SK' THEN 'SASKATCHEWAN'
    ELSE SUPPLIER_STATE
END
WHERE SUPPLIER_STATE IN ('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'GU', 'HI', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MO',
    'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NY', 'NV', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'AB', 'BC', 
    'ON', 'QC', 'SK');

