/* Instruction: To update the HOLDING_COMPANY where SUPPLIER_ERP is 'VERITAS COMMUNICATIONS' 
    and FISCAL YEAR is greater than or equal to FY_2022*/


-- Identify row count and total spend for the given supplier BEFORE and AFTER running the script.
SELECT
    FISCAL_YEAR,
    BUSINESS_GROUP,
    SUPPLIER_ERP,
    SUPPLIER_NORMALIZED,
    HOLDING_COMPANY,
    COUNT(BUSINESS_GROUP) AS ROW_COUNT,
    SUM(SPEND_USD) AS SPEND_USD
FROM SUB_SPEND_FINAL
WHERE SUPPLIER_ERP LIKE 'VERITAS COMMUNICATIONS'
GROUP BY 
    FISCAL_YEAR,
    BUSINESS_GROUP,
    SUPPLIER_ERP,
    SUPPLIER_NORMALIZED,
    HOLDING_COMPANY
ORDER BY FISCAL_YEAR DESC;
    
-- Update HOLDING_COMPANY field to 'STAGWELL' for specific suppliers in the FAF business group
UPDATE SUB_SPEND_FINAL
SET HOLDING_COMPANY = 'STAGWELL'
WHERE SUPPLIER_ERP = 'VERITAS COMMUNICATIONS'
    AND BUSINESS_GROUP = 'FAF' AND FISCAL_YEAR IN ('FY_2022', 'FY_2023', 'FY_2024');