--step 1 

UPDATE TBC_SPEND_FINAL
SET EXCHANGE_RATE_CURRENCY = 'USD',
    SUPPLIER_COUNTRY = 'UNITED STATES'
WHERE EXCHANGE_RATE_CURRENCY IS NULL 
AND SUPPLIER_COUNTRY IS NULL;

UPDATE TBC_SPEND_FINAL
SET SUPPLIER_COUNTRY = 'UNITED STATES'
WHERE SOURCE_SYSTEM = 'SAP' 
AND SUPPLIER_COUNTRY IS NULL;

COMMIT;

--step 2

-- 2.1 Create the table structure

CREATE TABLE TBC_UPDATE_TABLE
(
    ASSETID VARCHAR2(4000 BYTE),	
    BUYER_ID VARCHAR2(4000 BYTE),
    EXPENSE_TYPE VARCHAR2(4000 BYTE),    
    TRANSACTION_DATE VARCHAR2(4000 BYTE),
    TOTAL_SPEND_USD NUMBER(38,2),
    SUPPLIER_ERP VARCHAR2(4000 BYTE),
    SUPPLIER_COUNTRY VARCHAR2(4000 BYTE)
);

SELECT * FROM DF_TBC_UPDATE_TABLE;

--2.2 Upload the csv file into TBC_UPDATE_TABLE

--2.3 Run the merge script

MERGE INTO TBC_SPEND_FINAL FINAL 
USING (
    SELECT 
        BUYER_ID, EXPENSE_TYPE, TRANSACTION_DATE, TOTAL_SPEND_USD, ASSETID, SUPPLIER_COUNTRY
    FROM 
        TBC_UPDATE_TABLE
) SOURCE
ON (FINAL.BUYER_ID = SOURCE.BUYER_ID 
    AND FINAL.EXPENSE_TYPE = SOURCE.EXPENSE_TYPE
    AND FINAL.TRANSACTION_DATE = SOURCE.TRANSACTION_DATE
    AND FINAL.TOTAL_SPEND_USD = SOURCE.TOTAL_SPEND_USD
    AND FINAL.ASSETID = SOURCE.ASSETID)
WHEN MATCHED THEN 
    UPDATE SET FINAL.SUPPLIER_COUNTRY = SOURCE.SUPPLIER_COUNTRY;
    
-- 2.4 Drop the update table

DROP TABLE TBC_UPDATE_TABLE;